export const SELECTED_COUNTRIES = [
	'France',
	'Italy',
	'Poland',
	'Germany',
	'Thailand',
	'Vietnam',
	'United Arab Emirates',
	'Turkey',
	'Netherlands',
	'Czech Republic',
	'Republic of Serbia',
	'Montenegro',
	'Bosnia and Herzegovina',
	'Belgium',
	'Lithuania',
	'Georgia',
	'Sweden',
]
